title: Welcome to my page!
theme: jekyll-theme-leap-day
repositoryName: bpelikan.github.io
url: https://bpelikan.github.io/
homepageUrl: https://bpelikan.github.io/

github:
  repository_url: https://github.com/bpelikan