title: Bartosz Pelikan
description: 
theme: jekyll-theme-minimal
repositoryName: bpelikan.github.io
url: https://www.bartoszpelikan.pl/
homepageUrl: https://bpelikan.github.io/
logo: https://avatars1.githubusercontent.com/u/24376947?s=460&v=4
logo_redirect_url: https://www.bartoszpelikan.pl/
google_analytics: UA-149452518-1
githubProfile: https://github.com/bpelikan
linkedinProfile: https://www.linkedin.com/in/bartoszpelikan/
pluralsightProfile: https://app.pluralsight.com/profile/bpelikan
MSLearnProfile: http://docs.microsoft.com/users/bpelikan
stackoverflowProfile: https://stackoverflow.com/users/7906945/

github:
  repository_url: https://github.com/bpelikan
  is_project_page: true
  is_user_page: false
  owner_url: https://github.com/bpelikan
  owner_name: Bartosz Pelikan
